sudo: false
language: node_js
node_js:
  - '15'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
    - e2e/node_modules
before_install:
  - npm update
install:
  - npm install
  - npm run build
  - npm pack
  - cd e2e && npm install
script:
  - npm run test
